<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Task</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
</head>
<body class="bg-gray-100">

    <div class="container mx-auto text-center mt-20">
    <h1 class="text-4xl font-bold text-blue-700 mb-6">Task Successfully Deleted 😊</h1>

    </div>

    <div class="container mx-auto mt-10">
        <form method="get" action="/SPRINT3_MVC/web/">
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Back to Home</button>
        </form>
    </div>

</body>
</html>