<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar Tarea</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100">

    <div class="container mx-auto text-center mt-20">
    <h1 class="text-4xl font-bold text-blue-700 mb-6">Tarea Eliminada Correctamente 😊</h1>
    </div>

    <div class="container mx-auto mt-10">
        <form method="get" action= "../web/">
            <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Regresar</button>
        </form>
    </div>

</body>
</html>