<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>App Listas de Tareas</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css">
    <style>
    </style>
</head>
<body class="bg-gray-100 font-sans">
    <header class="bg-blue-500 p-4 text-white">
        <h1 class="text-2xl font-bold text-center">App Listas de Tareas</h1>
    </header>
    <main>
        <?php echo $this->content(); ?>
    </main>
    <footer class="bg-blue-500 p-4 text-white text-center">
        <p>&copy; <?php echo date("Y"); ?> ToDo List App. All rights reserved.</p>
    </footer>
</body>
</html>